### ISSUE TITLE
NPM Start Error - When Starting Server

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#34]
```
[nodemon] starting `node server.js`
D:\Users\Documents\GitHub\AskArya-Node.js-Vue.js\server\node_modules\express\lib\router\route.js:202
        throw new Error(msg);
        ^

Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.(anonymous function) [as post] (D:\Users\Documents\GitHub\AskArya-Node.js-Vue.js\server\node_modules\express\lib\router\route.js:202:15)
    at Function.proto.(anonymous function) [as post] (D:\Users\Documents\GitHub\AskArya-Node.js-Vue.js\server\node_modules\express\lib\router\index.js:510:19)
    at Object.<anonymous> (D:\Users\Documents\GitHub\AskArya-Node.js-Vue.js\server\app\routes\api\api-v1\public.js:18:8)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\Users\Documents\GitHub\AskArya-Node.js-Vue.js\server\app\routes\api\api-v1\index.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\Users\Documents\GitHub\AskArya-Node.js-Vue.js\server\app\routes\api\index.js:17:15)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by arya107** [comment]
```
Aryas-MacBook-Air-5:server arya$ npm start

> askarya-nodejs@1.0.0 start /Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server
> nodemon server.js

[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/node_modules/express/lib/router/route.js:202
        throw new Error(msg);
        ^

Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.(anonymous function) [as post] (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/node_modules/express/lib/router/route.js:202:15)
    at Function.proto.(anonymous function) [as post] (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/node_modules/express/lib/router/index.js:510:19)
    at Object.<anonymous> (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/app/routes/api/api-v1/public.js:18:8)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/app/routes/api/api-v1/index.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/app/routes/api/index.js:17:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by arya107** [comment]
```
 69% building 1607/1611 modules 4 active ...t/node_modules/d3-scale/src/cons 69% building 1608/1611 modules 3 active ...t/node_modules/d3-scale/src/cons 69% building 1609/1611 modules 2 active ..._modules/datamaps/node_modules/d 69% building 1609/1612 modules 3 active ...-interpolate/src/transform/decom 69% building 1610/1612 modules 2 active ..._modules/datamaps/node_modules/d 69% building 1611/1612 modules 1 active ...rc/assets/sass/black-dashboard-p 98% after emitting CopyPlugin                                    

 ERROR  Failed to compile with 3 errors                                                                              11:02:10 AM

These dependencies were not found:

* nprogress in ./src/main.js, ./src/backend.js
* nprogress/nprogress.css in ./src/main.js

To install them, you can run: npm install --save nprogress nprogress/nprogress.css
 

```
