### ISSUE TITLE
Server - NPM Start ERROR

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#48]
```
Aryas-MacBook-Air-5:server arya$ npm start

> askarya-nodejs@1.0.0 start /Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server
> nodemon server.js

[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/app/http/controllers/controller.js:14
    this.recaptcha = new Recaptcha(
                     ^

TypeError: Recaptcha is not a constructor
    at courseController.recaptchaConfig (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/app/http/controllers/controller.js:14:22)
    at new controller (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/app/http/controllers/controller.js:10:10)
    at new courseController (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/app/http/controllers/admin/adminController.js:3:1)
    at Object.<anonymous> (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/app/http/controllers/admin/adminController.js:19:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/app/routes/web/admin.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/arya/Documents/GitHub/AskArya-Node.js-Vue.js/Server/app/routes/web/index.js:32:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by arya107** [comment]
This error is visible in the new 2.1.0.6 github version

**Comment by abedi-ir** [comment]
salam,   
benazar mirese in issue ro dar commit bac67e198efbb76fb121bedd0449442f7ddf4f84 hal karede bashin.   
dar sourati ko moshkel bartarf shode ast, lotfan issue ro bebandin.

**Comment by arya107** [comment]
Harvaght express-recaptcha   az versione 4.1.1  e versione   5.0.0  update mikoni to Server folder, in error pish miyad

**Comment by yeganemehr** [comment]
bale in moshkel tabaee hast chon az version 4 ta 5 daraye breaking change haye mokhtalef hast va asasan shoma nabayad aslan hich kodom az package haro major update konid.
